version: '2.1'

services:
  tmckillop95:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctsprod.azurecr.io/labs/tmckillop95
    ports:
      - $SERVER_PORT:$SERVER_PORT
